# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from lovot_nav.protobufs import navigation_pb2 as navigation__pb2
from lovot_nav.protobufs import rpc_pb2 as rpc__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app_navigation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NavigationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResetMap = channel.unary_unary(
                '/lovot_app_api.NavigationService/ResetMap',
                request_serializer=rpc__pb2.ResetMapRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetUnwelcomedArea = channel.unary_unary(
                '/lovot_app_api.NavigationService/SetUnwelcomedArea',
                request_serializer=rpc__pb2.SetUnwelcomedAreaRequest.SerializeToString,
                response_deserializer=navigation__pb2.UnwelcomedArea.FromString,
                _registered_method=True)
        self.SetSpotCoordinate = channel.unary_unary(
                '/lovot_app_api.NavigationService/SetSpotCoordinate',
                request_serializer=rpc__pb2.SetSpotCoordinateRequest.SerializeToString,
                response_deserializer=navigation__pb2.Spot.FromString,
                _registered_method=True)
        self.DeleteSpot = channel.unary_unary(
                '/lovot_app_api.NavigationService/DeleteSpot',
                request_serializer=rpc__pb2.DeleteSpotRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetLovotPose = channel.unary_unary(
                '/lovot_app_api.NavigationService/GetLovotPose',
                request_serializer=rpc__pb2.GetLovotPoseRequest.SerializeToString,
                response_deserializer=navigation__pb2.Pose.FromString,
                _registered_method=True)
        self.GetDestination = channel.unary_unary(
                '/lovot_app_api.NavigationService/GetDestination',
                request_serializer=rpc__pb2.GetDestinationRequest.SerializeToString,
                response_deserializer=navigation__pb2.Pose.FromString,
                _registered_method=True)
        self.SetDestination = channel.unary_unary(
                '/lovot_app_api.NavigationService/SetDestination',
                request_serializer=rpc__pb2.SetDestinationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteDestination = channel.unary_unary(
                '/lovot_app_api.NavigationService/DeleteDestination',
                request_serializer=rpc__pb2.DeleteDestinationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class NavigationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResetMap(self, request, context):
        """地図をリセットする
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUnwelcomedArea(self, request, context):
        """来ないでエリアを更新する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpotCoordinate(self, request, context):
        """スポットの座標を更新する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSpot(self, request, context):
        """スポットを削除する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLovotPose(self, request, context):
        """LOVOT の自己位置を取得する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDestination(self, request, context):
        """LOVOT の目的地を取得する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDestination(self, request, context):
        """LOVOT の目的地を設定する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDestination(self, request, context):
        """LOVOT の目的地を削除する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NavigationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetMap,
                    request_deserializer=rpc__pb2.ResetMapRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetUnwelcomedArea': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUnwelcomedArea,
                    request_deserializer=rpc__pb2.SetUnwelcomedAreaRequest.FromString,
                    response_serializer=navigation__pb2.UnwelcomedArea.SerializeToString,
            ),
            'SetSpotCoordinate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpotCoordinate,
                    request_deserializer=rpc__pb2.SetSpotCoordinateRequest.FromString,
                    response_serializer=navigation__pb2.Spot.SerializeToString,
            ),
            'DeleteSpot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSpot,
                    request_deserializer=rpc__pb2.DeleteSpotRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetLovotPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLovotPose,
                    request_deserializer=rpc__pb2.GetLovotPoseRequest.FromString,
                    response_serializer=navigation__pb2.Pose.SerializeToString,
            ),
            'GetDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDestination,
                    request_deserializer=rpc__pb2.GetDestinationRequest.FromString,
                    response_serializer=navigation__pb2.Pose.SerializeToString,
            ),
            'SetDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDestination,
                    request_deserializer=rpc__pb2.SetDestinationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDestination,
                    request_deserializer=rpc__pb2.DeleteDestinationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lovot_app_api.NavigationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lovot_app_api.NavigationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NavigationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lovot_app_api.NavigationService/ResetMap',
            rpc__pb2.ResetMapRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetUnwelcomedArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lovot_app_api.NavigationService/SetUnwelcomedArea',
            rpc__pb2.SetUnwelcomedAreaRequest.SerializeToString,
            navigation__pb2.UnwelcomedArea.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpotCoordinate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lovot_app_api.NavigationService/SetSpotCoordinate',
            rpc__pb2.SetSpotCoordinateRequest.SerializeToString,
            navigation__pb2.Spot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSpot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lovot_app_api.NavigationService/DeleteSpot',
            rpc__pb2.DeleteSpotRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLovotPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lovot_app_api.NavigationService/GetLovotPose',
            rpc__pb2.GetLovotPoseRequest.SerializeToString,
            navigation__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lovot_app_api.NavigationService/GetDestination',
            rpc__pb2.GetDestinationRequest.SerializeToString,
            navigation__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lovot_app_api.NavigationService/SetDestination',
            rpc__pb2.SetDestinationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lovot_app_api.NavigationService/DeleteDestination',
            rpc__pb2.DeleteDestinationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
