# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app-navigation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app-navigation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from lovot_nav.protobufs import navigation_pb2 as navigation__pb2
from lovot_nav.protobufs import rpc_pb2 as rpc__pb2
from protoc_gen_swagger.options import annotations_pb2 as protoc__gen__swagger_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pp-navigation.proto\x12\rlovot_app_api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10navigation.proto\x1a\trpc.proto\x1a,protoc-gen-swagger/options/annotations.proto2\xfa\x07\n\x11NavigationService\x12\x66\n\x08ResetMap\x12!.lovot.navigation.ResetMapRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/v1/maps/{map_id}/reset\x12\x9a\x01\n\x11SetUnwelcomedArea\x12*.lovot.navigation.SetUnwelcomedAreaRequest\x1a .lovot.navigation.UnwelcomedArea\"7\x82\xd3\xe4\x93\x02\x31\x1a,/v1/maps/{map_id}/unwelcomed_areas/{area_id}:\x01*\x12\x87\x01\n\x11SetSpotCoordinate\x12*.lovot.navigation.SetSpotCoordinateRequest\x1a\x16.lovot.navigation.Spot\".\x82\xd3\xe4\x93\x02(\"#/v1/maps/{map_id}/spots/{spot_name}:\x01*\x12v\n\nDeleteSpot\x12#.lovot.navigation.DeleteSpotRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%*#/v1/maps/{map_id}/spots/{spot_name}\x12p\n\x0cGetLovotPose\x12%.lovot.navigation.GetLovotPoseRequest\x1a\x16.lovot.navigation.Pose\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/navigation/lovot_pose\x12u\n\x0eGetDestination\x12\'.lovot.navigation.GetDestinationRequest\x1a\x16.lovot.navigation.Pose\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/navigation/destination\x12x\n\x0eSetDestination\x12\'.lovot.navigation.SetDestinationRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f\"\x1a/v1/navigation/destination:\x01*\x12{\n\x11\x44\x65leteDestination\x12*.lovot.navigation.DeleteDestinationRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/navigation/destinationB.Z,github.com/groove-x/lovot-apis/lovot-app-apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_navigation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/groove-x/lovot-apis/lovot-app-api'
  _globals['_NAVIGATIONSERVICE'].methods_by_name['ResetMap']._loaded_options = None
  _globals['_NAVIGATIONSERVICE'].methods_by_name['ResetMap']._serialized_options = b'\202\323\344\223\002\031\"\027/v1/maps/{map_id}/reset'
  _globals['_NAVIGATIONSERVICE'].methods_by_name['SetUnwelcomedArea']._loaded_options = None
  _globals['_NAVIGATIONSERVICE'].methods_by_name['SetUnwelcomedArea']._serialized_options = b'\202\323\344\223\0021\032,/v1/maps/{map_id}/unwelcomed_areas/{area_id}:\001*'
  _globals['_NAVIGATIONSERVICE'].methods_by_name['SetSpotCoordinate']._loaded_options = None
  _globals['_NAVIGATIONSERVICE'].methods_by_name['SetSpotCoordinate']._serialized_options = b'\202\323\344\223\002(\"#/v1/maps/{map_id}/spots/{spot_name}:\001*'
  _globals['_NAVIGATIONSERVICE'].methods_by_name['DeleteSpot']._loaded_options = None
  _globals['_NAVIGATIONSERVICE'].methods_by_name['DeleteSpot']._serialized_options = b'\202\323\344\223\002%*#/v1/maps/{map_id}/spots/{spot_name}'
  _globals['_NAVIGATIONSERVICE'].methods_by_name['GetLovotPose']._loaded_options = None
  _globals['_NAVIGATIONSERVICE'].methods_by_name['GetLovotPose']._serialized_options = b'\202\323\344\223\002\033\022\031/v1/navigation/lovot_pose'
  _globals['_NAVIGATIONSERVICE'].methods_by_name['GetDestination']._loaded_options = None
  _globals['_NAVIGATIONSERVICE'].methods_by_name['GetDestination']._serialized_options = b'\202\323\344\223\002\034\022\032/v1/navigation/destination'
  _globals['_NAVIGATIONSERVICE'].methods_by_name['SetDestination']._loaded_options = None
  _globals['_NAVIGATIONSERVICE'].methods_by_name['SetDestination']._serialized_options = b'\202\323\344\223\002\037\"\032/v1/navigation/destination:\001*'
  _globals['_NAVIGATIONSERVICE'].methods_by_name['DeleteDestination']._loaded_options = None
  _globals['_NAVIGATIONSERVICE'].methods_by_name['DeleteDestination']._serialized_options = b'\202\323\344\223\002\034*\032/v1/navigation/destination'
  _globals['_NAVIGATIONSERVICE']._serialized_start=174
  _globals['_NAVIGATIONSERVICE']._serialized_end=1192
# @@protoc_insertion_point(module_scope)
