# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wifi-fingerprint.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import wifi_pb2 as wifi__pb2
import tf_pb2 as tf__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wifi-fingerprint.proto',
  package='lovot_localization',
  syntax='proto3',
  serialized_options=b'Z1github.com/groove-x/lovot-apis/lovot-localization',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16wifi-fingerprint.proto\x12\x12lovot_localization\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\nwifi.proto\x1a\x08tf.proto\"G\n\nCovariance\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06matrix\x18\x02 \x03(\x02\"t\n\x0bReliability\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0breliability\x18\x02 \x01(\x02\x12\x11\n\tdetection\x18\x03 \x01(\x02\x12\x12\n\nlikelihood\x18\x04 \x01(\x02\"\xa9\x02\n\x13TransformEstimation\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\ttransform\x18\x02 \x01(\x0b\x32\x16.lovot_tf.tf.Transform\x12\x0e\n\x06map_id\x18\x03 \x01(\t\x12\x10\n\x08map_name\x18\x04 \x01(\t\x12\x30\n\tlocalizer\x18\x05 \x01(\x0e\x32\x1d.lovot_localization.Localizer\x12\x32\n\ncovariance\x18\x06 \x01(\x0b\x32\x1e.lovot_localization.Covariance\x12\x34\n\x0breliability\x18\x07 \x01(\x0b\x32\x1f.lovot_localization.Reliability\"\x9c\x02\n\x0b\x46ingerprint\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12H\n\raccess_points\x18\x03 \x03(\x0b\x32\x31.lovot_localization.Fingerprint.AccessPointsEntry\x12:\n\ttransform\x18\x04 \x01(\x0b\x32\'.lovot_localization.TransformEstimation\x1aI\n\x11\x41\x63\x63\x65ssPointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.lovot_minid.wifi.AP:\x02\x38\x01\"A\n\x08RadioMap\x12\x35\n\x0c\x66ingerprints\x18\x01 \x03(\x0b\x32\x1f.lovot_localization.Fingerprint*,\n\tLocalizer\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06VISUAL\x10\x01\x12\t\n\x05\x44\x45PTH\x10\x02\x42\x33Z1github.com/groove-x/lovot-apis/lovot-localizationb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,wifi__pb2.DESCRIPTOR,tf__pb2.DESCRIPTOR,])

_LOCALIZER = _descriptor.EnumDescriptor(
  name='Localizer',
  full_name='lovot_localization.Localizer',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VISUAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEPTH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=946,
  serialized_end=990,
)
_sym_db.RegisterEnumDescriptor(_LOCALIZER)

Localizer = enum_type_wrapper.EnumTypeWrapper(_LOCALIZER)
NONE = 0
VISUAL = 1
DEPTH = 2



_COVARIANCE = _descriptor.Descriptor(
  name='Covariance',
  full_name='lovot_localization.Covariance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='lovot_localization.Covariance.stamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matrix', full_name='lovot_localization.Covariance.matrix', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=172,
)


_RELIABILITY = _descriptor.Descriptor(
  name='Reliability',
  full_name='lovot_localization.Reliability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='lovot_localization.Reliability.stamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reliability', full_name='lovot_localization.Reliability.reliability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detection', full_name='lovot_localization.Reliability.detection', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='likelihood', full_name='lovot_localization.Reliability.likelihood', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=290,
)


_TRANSFORMESTIMATION = _descriptor.Descriptor(
  name='TransformEstimation',
  full_name='lovot_localization.TransformEstimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='lovot_localization.TransformEstimation.stamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transform', full_name='lovot_localization.TransformEstimation.transform', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_id', full_name='lovot_localization.TransformEstimation.map_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_name', full_name='lovot_localization.TransformEstimation.map_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='localizer', full_name='lovot_localization.TransformEstimation.localizer', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='lovot_localization.TransformEstimation.covariance', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reliability', full_name='lovot_localization.TransformEstimation.reliability', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=590,
)


_FINGERPRINT_ACCESSPOINTSENTRY = _descriptor.Descriptor(
  name='AccessPointsEntry',
  full_name='lovot_localization.Fingerprint.AccessPointsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='lovot_localization.Fingerprint.AccessPointsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='lovot_localization.Fingerprint.AccessPointsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=804,
  serialized_end=877,
)

_FINGERPRINT = _descriptor.Descriptor(
  name='Fingerprint',
  full_name='lovot_localization.Fingerprint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='lovot_localization.Fingerprint.stamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='lovot_localization.Fingerprint.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='access_points', full_name='lovot_localization.Fingerprint.access_points', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transform', full_name='lovot_localization.Fingerprint.transform', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FINGERPRINT_ACCESSPOINTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=877,
)


_RADIOMAP = _descriptor.Descriptor(
  name='RadioMap',
  full_name='lovot_localization.RadioMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fingerprints', full_name='lovot_localization.RadioMap.fingerprints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=879,
  serialized_end=944,
)

_COVARIANCE.fields_by_name['stamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RELIABILITY.fields_by_name['stamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TRANSFORMESTIMATION.fields_by_name['stamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TRANSFORMESTIMATION.fields_by_name['transform'].message_type = tf__pb2._TRANSFORM
_TRANSFORMESTIMATION.fields_by_name['localizer'].enum_type = _LOCALIZER
_TRANSFORMESTIMATION.fields_by_name['covariance'].message_type = _COVARIANCE
_TRANSFORMESTIMATION.fields_by_name['reliability'].message_type = _RELIABILITY
_FINGERPRINT_ACCESSPOINTSENTRY.fields_by_name['value'].message_type = wifi__pb2._AP
_FINGERPRINT_ACCESSPOINTSENTRY.containing_type = _FINGERPRINT
_FINGERPRINT.fields_by_name['stamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FINGERPRINT.fields_by_name['access_points'].message_type = _FINGERPRINT_ACCESSPOINTSENTRY
_FINGERPRINT.fields_by_name['transform'].message_type = _TRANSFORMESTIMATION
_RADIOMAP.fields_by_name['fingerprints'].message_type = _FINGERPRINT
DESCRIPTOR.message_types_by_name['Covariance'] = _COVARIANCE
DESCRIPTOR.message_types_by_name['Reliability'] = _RELIABILITY
DESCRIPTOR.message_types_by_name['TransformEstimation'] = _TRANSFORMESTIMATION
DESCRIPTOR.message_types_by_name['Fingerprint'] = _FINGERPRINT
DESCRIPTOR.message_types_by_name['RadioMap'] = _RADIOMAP
DESCRIPTOR.enum_types_by_name['Localizer'] = _LOCALIZER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Covariance = _reflection.GeneratedProtocolMessageType('Covariance', (_message.Message,), {
  'DESCRIPTOR' : _COVARIANCE,
  '__module__' : 'wifi_fingerprint_pb2'
  # @@protoc_insertion_point(class_scope:lovot_localization.Covariance)
  })
_sym_db.RegisterMessage(Covariance)

Reliability = _reflection.GeneratedProtocolMessageType('Reliability', (_message.Message,), {
  'DESCRIPTOR' : _RELIABILITY,
  '__module__' : 'wifi_fingerprint_pb2'
  # @@protoc_insertion_point(class_scope:lovot_localization.Reliability)
  })
_sym_db.RegisterMessage(Reliability)

TransformEstimation = _reflection.GeneratedProtocolMessageType('TransformEstimation', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORMESTIMATION,
  '__module__' : 'wifi_fingerprint_pb2'
  # @@protoc_insertion_point(class_scope:lovot_localization.TransformEstimation)
  })
_sym_db.RegisterMessage(TransformEstimation)

Fingerprint = _reflection.GeneratedProtocolMessageType('Fingerprint', (_message.Message,), {

  'AccessPointsEntry' : _reflection.GeneratedProtocolMessageType('AccessPointsEntry', (_message.Message,), {
    'DESCRIPTOR' : _FINGERPRINT_ACCESSPOINTSENTRY,
    '__module__' : 'wifi_fingerprint_pb2'
    # @@protoc_insertion_point(class_scope:lovot_localization.Fingerprint.AccessPointsEntry)
    })
  ,
  'DESCRIPTOR' : _FINGERPRINT,
  '__module__' : 'wifi_fingerprint_pb2'
  # @@protoc_insertion_point(class_scope:lovot_localization.Fingerprint)
  })
_sym_db.RegisterMessage(Fingerprint)
_sym_db.RegisterMessage(Fingerprint.AccessPointsEntry)

RadioMap = _reflection.GeneratedProtocolMessageType('RadioMap', (_message.Message,), {
  'DESCRIPTOR' : _RADIOMAP,
  '__module__' : 'wifi_fingerprint_pb2'
  # @@protoc_insertion_point(class_scope:lovot_localization.RadioMap)
  })
_sym_db.RegisterMessage(RadioMap)


DESCRIPTOR._options = None
_FINGERPRINT_ACCESSPOINTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
